### ISSUE TITLE
Seed number not showing in console.

### ISSUE THREAD

**Issue by furiodjeex** [npruehs/bychance#6]
Hi. I have purchased By Chance Level Generator.  I'm so far very happy with it. 
Maybe I'm missing something, but the seed number is not showing in the console, even though I have the box "log Level Generation" checked on!  It is not showing on the example scene provided with the level generator also. I have seen it on the video tutorial and read about it in the manual.
Is this a bug or am I missing something? Where is this seed number generate? In which script?
Thanks in advance.

**Comment by npruehs** [comment]
You're right - that's a bug. It has been introduced with the asynchronous level generation with progress bars.

The random number generator is initialized in ByChangeLevelGenerator.GenerateLevelIteration, line 305. You could log the seed there if you'd like, try something like:

`Debug.Log("Seed: " + this.random.Seed);`

Sorry for the inconvenience - this will be fixed in the next release.

**Comment by furiodjeex** [comment]
Works like a charm! Thanks a lot!

**Comment by npruehs** [comment]
New version has been submitted to the asset store. Your fix will be available as soon as the submission has passed.
